config/routes.rb
Rails.application.routes.draw do
  resources :pets
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'index#home'
	get 'home' => 'index#home'
	get 'busca' => 'pets#busca'
	get 'petcadastro' => 'pets#petcadastro'
        get 'listabusca' => 'pets#listabusca'
        post 'perfil' => 'pets#busca_perfil'
	post 'cadastro' => 'pets#create'
	resources :pets
	resources :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord

	validates :doadornome, presence: {message: "não pode estar vazio"}
	validates :doadoremail, presence: {message: "não pode estar vazio"}
	validates :petnome, presence: {message: "não pode estar vazio"}
	validates :petraca, presence: {message: "não pode estar vazio"}
	validates :petobservacoes, presence: {message: "não pode estar vazio"}
	validates :petidade, presence: {message: "não pode estar vazio"}
	validates :pettamanho, presence: {message: "não pode estar vazio"}
	

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	def hello
	render html: '<h1>Acolha um amigo</h1>
		<img src="http://tudosobrecachorros.com.br/wp-content/uploads/precos-de-cachorro.png"/>'.html_safe

end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  
  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  def listabusca
 @pets = Pet.all
  end
  # GET /pets/1
  # GET /pets/1.json
  def show
    @pets = Pet.all
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to home_path, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { redirect_to petcadastro_path, notice: 'Pet was not successfully created.' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

def busca_perfil

  respond_to do |format|
session[:nome]=params[:session][:nome]
        session[:email]=params[:session][:email]
      if !params[:session][:nome].empty? && !params[:session][:email].empty?
        
        session[:apartamento]=params[:session][:apartamento]
        params[:session][:condominio]=params[:session][:condominio]
        params[:session][:areapet]=params[:session][:areapet]
        params[:session][:horalivre]=params[:session][:horalivre]
        params[:session][:crianca]=params[:session][:crianca]
        params[:session][:caosozinho]=params[:session][:caosozinho]
        params[:session][:caosala]=params[:session][:caosala]
        params[:session][:renda]=params[:session][:renda]
       format.html {  redirect_to listabusca_path, notice: 'Usuario logado com sucesso' }
       format.json { }
     else
       format.html {  redirect_to busca_path, error: 'Insira um nome e um email' }
       format.json { }
      end
    end

end


  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:doadornome, :doadoremail, :petnome, :petraca, :petimagem, :petimagem_url, :petobservacoes, :petinsercao, :petidade, :pettamanho, :petchora, :petsegue, :petagitado, :petlateestranhos, :petavanca, :petproblemassaude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def pageTitle(name)
 default = "Acolha um Amigo"
  if name.empty?
   return  default
  else
   return default
end
end


end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/index/home.html.erb
<div class="wag-header" id="home">
  <div class="container">
    <div class="col-md-12">

      <h1 class="wag-intro text-center">Dê um novo lar a um novo amigo</div>
    <div class="col-md-8 col-md-offset-2">
      <p class="wag-explain text-center"></p>

      <div class="wag-buttons text-center">
        <ul class="list-inline">
          <li><a class="btn" href="busca.html" role="button">Acolha</a></li>
          <li><a class="btn" href="petcadastro.html" role="button">Aliste um Pet</a></li>
        </ul>
      </div>
    </div>
  </div>

</div>

<div id="about-us">
  <div class="container">
    <div class="row">
      
      <div class="col-lg-12">
        <h2 class="about-header text-center">Quem somos nós</h2>
      </div>
      
        
      <div class="col-md-6">
        <h3 class="about-h3"><strong>Acolha um amigo é um projeto que visa diminuir o número de abandono de animais.</strong></h3>
        <P class="about-p"><strong>O abandono animal é um problema atual da sociedade. Os motivos são diversos: animal teve cria, donos não conseguem mais cuidar, mudança de residência, etc. Muitas instituições os acolhem, mas enfrentam problemas de superlotação. Além disso, toda a divulgação de animais para adoção é dispersa (por meio de redes sociais, páginas específicas das instituições, dentre outros), o que por sua vez dificulta as buscas. </strong></P>
         <P class="about-p"><strong>Acolha um amigo é um projeto que visa a criação de uma plataforma unificada para divulgação de animais para adoção. Nessa plataforma, instituições e pessoas que recolhem animais podem divulgar os mesmos, de forma unificada.</strong> </P>
       
      </div>
      
      <div class="col-md-6">
        <img class="pretty-gurl img-responsive" src="http://gdurl.com/ClMK">
      </div>
    
  </div>
</div>
</div>

<div class="services-section" id="missao">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2 id="head1">Missão</h2>
      </div>
      <div class="col-md-offset-2 col-md-8 text-center">
        <h4 class="phead">Acolha um amigo é uma plataforma voltada à divulgação de animais paraadoção. Será possível realizar buscas de animais, baseadas nas características de quem deseja adotar e do animal a ser adotado
        </h4>
      </div>


      <div class="col-md-4">
        <div class="awesome">
          <i class="fa fa-home fa-4x"></i>
        </div>
        <h3><strong>Adote</strong></h3>
        <p><strong>Adotar  é dar um novo lar aos bichinhos e você ainda ganha novos amigos.</strong>
        </p>
        <div class="serv-ice">
          <a class="btn btn-lg" href="busca.html" role="button">Acolha</a>
        </div>
      </div>

      <div class="col-md-4">
        <div class="awesome">
          <i class="fa fa-futbol-o fa-4x"></i>
        </div>
        <h3><strong>Qual o animal ideal ?</strong></h3>
        <p><strong>Através de uma inteligencia artificial nos traçamos o perfil ideal de cachorro para você ! </strong>
        </p>
        <div class="serv-ice">
          <a class="btn btn-lg" href="#about-us" role="button">Sobre</a>
        </div>
      </div>


      <div class="col-md-4">
        <div class="awesome">
          <i class="fa fa-comment fa-4x"></i>
        </div>
        <h3><strong>Dúvidas</strong></h3>
        <p><strong>Qualquer dúvida, crítica ou sugestão, entre em contato conosco clicando no link abaixo.</strong>
        </p>
        <div class="serv-ice">
          <a class="btn btn-lg" href="#contato" role="button">Contato</a>
        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>
  </div>

     <div class="ourreal-customers">
       <div class="container">
         <div class="row">
           
           <div class="col-md-8 col-md-offset-2">
             <h2 class="real-h2">Veja quem adotou</h2>
           </div>
           
           <div class="col-md-4">
             <div class="shield">
               <img class="prove img-responsive img-circle" src="https://raymondhw.github.io/images/familyreview.jpg">
               <h3>Ricardo</h3>
               <p>"Eu e minha familia sempre sonhamos em ter um cachorro, mas nunca soubemos qual queriamos até encontrar esse site"</p>
             </div>
           </div>
           
            
           <div class="col-md-4">
               <div class="shield">
               <img class="prove img-responsive img-circle" src="https://raymondhw.github.io/images/familyreviewtwo.jpg">
               <h3>Katia Harume</h3>
               <p>"Antes de conhecer o Max, eu sempre me sentia sozinha em casa. Graças ao site hoje eu vejo que ele é o meu melhor amigo"</p>
             </div>
           </div>
           
            
           <div class="col-md-4">
               <div class="shield">
               <img class="prove img-responsive img-circle" src="https://raymondhw.github.io/images/familyreview.jpg">
               <h3>Ronaldo</h3>
               <p>"Sempre gostei de cachorros, mas nunca soube qual adotar, quando entrei no site e vi a proposta fiquei impressionado."</p>
             </div>
           </div>
           
           
         </div>
       </div>
</div>


  <div class="contact-us" id="contato">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="contact-head text-center">Contato</h2>
          <h4 class="contact-p text-center">Entre em contato conosco preenchendo o formulário abaixo.</h4>

        </div>
        <div class="col-md-8 col-md-offset-2">
          <form>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="firstname">Nome</label>
                  <input id="firstname" type="text" class="form-control">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="lastname">Sobrenome</label>
                  <input id="lastname" type="text" class="form-control">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="email">Email</label>
                  <input id="email" type="text" class="form-control">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="subject">Assunto</label>
                  <input id="subject" type="text" class="form-control">
                </div>
              </div>
              <div class="col-sm-12">
                <div class="form-group">
                  <label for="message">Mensagem</label>
                  <textarea id="message" class="form-control input-lg"></textarea>
                </div>
              </div>
              <div class="col-sm-12 text-center">
                <div class="formsend">
                  <button type="submit" class="btn btn-block"> Enviar</button>
                </div>

              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
  <div class="footer-section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
         <h3>Sobre nós </h3>
               <p>Acolha um amigo é um projeto que visa a criação de uma plataforma unificada para divulgação de animais para adoção. Nessa plataforma, instituições e pessoas que recolhem animais podem divulgar os mesmos, de forma unificada.</p>
               <p class="about-more"><a href="<%=home_path%>#about-us">Veja mais...</a></p>
        </div>

        

        <div class="col-md-4">
          <h3 class="footerh4">Mapa do Site</h3>
          <ul class="links">
            <li><a href="<%=home_path%>">Home</a></li>
            <li><a href="<%=home_path%>#contato">Contato</a></li>
            <li><a href="<%=home_path%>#missao">Missão</a></li>
            <li><a href="<%=busca_path%>">Adotar</a></li>
            <li><a href="<%=petcadastro_path%>">Aliste um bichinho</a></li>
          </ul>
        </div>
        
        


        <div class="col-md-4">
          <h3 class="footerh4">Entre em contato</h3>
          <p class="footerp">Entre em contato diretamente conosco e siga a gente nas redes sociais
          </p>

          <p class="yolk"><a href="jay503cool@gmail.com"><i class="fa fa-envelope-o"></i> acolhaAmigo@gmail.com</a></p>

          <p class="yolk"><a href="jay503cool@gmail.com"><i class="fa fa-phone"></i>(11) 94007-0100</a></p>
           <ul class="list-inline social-buttons">
       
                            <li><a href="#">
                              <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-2x"></i>
                            <i class="fa fa-facebook fa-stack-1x"></i>   
                            </a>
                            </li>
                            <li><a href="#">
                              <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-2x"></i>
                            <i class="fa fa-linkedin fa-stack-1x"></i>  
                            </a>
                            </li>
                               <li><a href="#">
                              <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-2x"></i>
                            <i class="fa fa-instagram fa-stack-1x"></i>  
                            </a>
                            </li>
                                      
                        </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'application' , 'data-turbolinks-track': 'reload' %>


<link rel="shortcut icon" type="image/png" href="https://raymondhw.github.io/images/dog-paw.png">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
      <a class="navbar-brand" href="<%=home_path%>"><img class="img-responsive pull-left" src="https://raymondhw.github.io/images/dog-paw.png" id="logo"> Acolha um amigo</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<%=busca_path%>">Adotar</a>
        </li>
        <li>
	<a href="<%=home_path%>#about-us">Sobre</a>
        </li>
        <li>
          <a href="<%=home_path%>#missao">Missão</a>
        </li>
        <li>
          <a href="<%=home_path%>#contato">Contato</a>
        </li>
        
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=pageTitle(yield(:title))%></title>
    <%= render 'layouts/head' %>
   
  </head>

  <body>
   <%= render 'layouts/header' %> 
   <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pets/busca.html.erb
    
     <div class="contact-us" id="contato">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="contact-head text-center">Adote um pet</h2>
          <h4 class="contact-p text-center">Olá, estamos quase lá, antes de você encontrar o pet ideal, você irá preencher alguns dados e clicar nas checkboxs caso as frases se encaixem no seu perfil, assim o nosso sistema consegue computar os cachorros ideais para você.  Desde já obrigado pelo seu bom coração.</h4>

        </div>
        <%= form_for(:session, url: perfil_path) do |f| %>
        <div class="col-md-8 col-md-offset-2">
          <form>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="name">Seu nome</label>
                  <%= f.text_field :nome, class: 'form-control',placeholder: session[:nome], value: session[:nome]%>
                  
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="email">Email</label>
                  <%= f.text_field :email, class: 'form-control',placeholder: session[:email],value: session[:email] %>
                </div>
              </div>
                
                
  <div class="col-lg-6">
      <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
         <%= f.check_box :apartamento, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder=" Moro em apartamento" disabled>
    </div><!-- /input-group -->
      </div>
  </div><!-- /.col-lg-6 -->
                
<div class="col-lg-6">
    <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
         <%= f.check_box :condominio, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Moro em um condominio" disabled >
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>

<div class= "col-lg-6">
    <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :areapet, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Tenho uma área para o futuro pet" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
                </div>
  <div class="col-lg-6">
      <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :horalivre, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Tenho mais de uma hora livre para o pet" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
                </div>
                
<div class="col-lg-6">
    <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :crianca, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Tenho criança(s) menor que 10 anos" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>
    <div class="col-lg-6">
<div class="form-group">
        <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :caosozinho, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Meu cão ficará mais de duas horas sozinho" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>
                
<div class="col-lg-6">
<div class="form-group">
        <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :caosala, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Meu cão poderá ficar na sala de estar" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>
                
                <div class="col-lg-6">
<div class="form-group">
        <div class="input-group">
      <span class="input-group-addon">
        <%= f.check_box :renda, {}, 1, 0 %>
      </span>
      <input type="text" class="form-control" placeholder="Renda maior que mil reais por pessoa" disabled>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>
                <div class="formsend">
                <%= f.submit "Procurar", class: "btn btn-block" %>
                </div>
                <%end%>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Doadornome</th>
      <th>Doadoremail</th>
      <th>Petnome</th>
      <th>Petraca</th>
      <th>Petimagem</th>
      <th>Petimagem url</th>
      <th>Petobservacoes</th>
      <th>Petinsercao</th>
      <th>Petidade</th>
      <th>Pettamanho</th>
      <th>Petchora</th>
      <th>Petsegue</th>
      <th>Petagitado</th>
      <th>Petlateestranhos</th>
      <th>Petavanca</th>
      <th>Petproblemassaude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.doadornome %></td>
        <td><%= pet.doadoremail %></td>
        <td><%= pet.petnome %></td>
        <td><%= pet.petraca %></td>
        <td><%= pet.petimagem %></td>
        <td><%= pet.petimagem_url %></td>
        <td><%= pet.petobservacoes %></td>
        <td><%= pet.petinsercao %></td>
        <td><%= pet.petidade %></td>
        <td><%= pet.pettamanho %></td>
        <td><%= pet.petchora %></td>
        <td><%= pet.petsegue %></td>
        <td><%= pet.petagitado %></td>
        <td><%= pet.petlateestranhos %></td>
        <td><%= pet.petavanca %></td>
        <td><%= pet.petproblemassaude %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/listabusca.html.erb
  <div class="contact-us" id="contato">    
<div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2 class="contact-head text-center">Pets encontrados</h2>
          <h4 class="contact-p text-center">Estes são os pets encontrados para o seu perfil, caso você queira mudar algum dado clique na opção limpar filtros.</h4>
        </div>
      </div>
 

<div class="home_runs  col-md-12 " >
<% @pets.each do |pet| %>
<div class="home_run col-md-8 col-md-offset-1 " >
                    
                    <div class="home_run_description  ">
                    <!-- Talvez dividir os itens em duas linhas -->
                    <ul class="home_run_description_list  ">
		<li class="home_rdl_user home_rdl_item">
                        <span class="fa fa-user"/> <b> Nome:</b> <%= pet.petnome%>
                    </li>                   

		    <li class="home_rdl_idade home_rdl_item">
                        <span class="fa fa-calendar"/> <b> Idade:</b> <%= pet.petidade%>
                    </li>
		      <li class="home_rdl_raca home_rdl_item">
                        <span class="fa fa-info"></span><b> Raça:</b> <%= pet.petraca%>
                    </li> 
                    <li class="home_rdl_saude home_rdl_item">
                   <span class="fa fa-heart" /><b> Saúde:</b> Saudável  </li>
                    </ul>
                    </div>
                    <div class="home_run_post "><%= pet.petobservacoes%>
                        </div>
	        <div class="home_run_submit"> 
		<button  type="submit" class="btn btn-success"> <b>Adotar</b> </button>	
		 <button  type="submit" class="btn btn-success"> <b>Limpar filtros</b> </button>	
	</div>
                    <div class="home_run_image ">
<!--                <a href = "/jogos/ jogada.jogo.id"><img  class="img-thumbnail " src="data:image/jpg;base64, jogada.jogo.imagem "></a>-->
             <img class="img-thumbnail" src="<%= pet.petimagem_url %> "> 

            </div>
           </div>
<%end%>

 </div>
</div>
</div>
</div>
</div>
</div>
</div>        

</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doadornome:</strong>
  <%= @pet.doadornome %>
</p>

<p>
  <strong>Doadoremail:</strong>
  <%= @pet.doadoremail %>
</p>

<p>
  <strong>Petnome:</strong>
  <%= @pet.petnome %>
</p>

<p>
  <strong>Petraca:</strong>
  <%= @pet.petraca %>
</p>

<p>
  <strong>Petimagem:</strong>
  <%= @pet.petimagem %>
</p>

<p>
  <strong>Petimagem url:</strong>
  <%= @pet.petimagem_url %>
</p>

<p>
  <strong>Petobservacoes:</strong>
  <%= @pet.petobservacoes %>
</p>

<p>
  <strong>Petinsercao:</strong>
  <%= @pet.petinsercao %>
</p>

<p>
  <strong>Petidade:</strong>
  <%= @pet.petidade %>
</p>

<p>
  <strong>Pettamanho:</strong>
  <%= @pet.pettamanho %>
</p>

<p>
  <strong>Petchora:</strong>
  <%= @pet.petchora %>
</p>

<p>
  <strong>Petsegue:</strong>
  <%= @pet.petsegue %>
</p>

<p>
  <strong>Petagitado:</strong>
  <%= @pet.petagitado %>
</p>

<p>
  <strong>Petlateestranhos:</strong>
  <%= @pet.petlateestranhos %>
</p>

<p>
  <strong>Petavanca:</strong>
  <%= @pet.petavanca %>
</p>

<p>
  <strong>Petproblemassaude:</strong>
  <%= @pet.petproblemassaude %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>